apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: antrea-operator
rules:
- apiGroups:
    - config.openshift.io
  resources:
    - clusteroperators
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - config.openshift.io
  resources:
    - clusteroperators/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
    - config.openshift.io
  resources:
    - networks
  verbs:
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - config.openshift.io
  resources:
    - networks/finalizers
  verbs:
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - operator.openshift.io
  resources:
    - networks
  verbs:
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - security.openshift.io
  resources:
    - securitycontextconstraints
  verbs:
    - use
