apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: antrea-operator
rules:
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ''
  resources:
  - endpoints
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - ''
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ''
  resources:
  - nodes
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ''
  resources:
  - nodes/status
  verbs:
  - patch
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ''
  resources:
  - pods/status
  verbs:
  - patch
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - create
  - get
  - patch
  - update
  - watch
- apiGroups:
  - ''
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ''
  resources:
  - services
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ''
  resources:
  - services/status
  verbs:
  - update
  - patch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - create
  - get
  - list
  - patch
  - update
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - create
  - get
  - list
  - patch
  - update
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apiregistration.k8s.io
  resources:
  - apiservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - list
  - patch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
  - patch
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
  - patch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests/approval
  verbs:
  - update
  - patch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests/status
  verbs:
  - update
  - patch
- apiGroups:
  - certificates.k8s.io
  resources:
  - signers
  verbs:
  - approve
  - sign
  - patch
- apiGroups:
  - controlplane.antrea.io
  resources:
  - addressgroups
  verbs:
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - controlplane.antrea.io
  resources:
  - appliedtogroups
  verbs:
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - controlplane.antrea.io
  resources:
  - egressgroups
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - controlplane.antrea.io
  resources:
  - networkpolicies
  verbs:
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - controlplane.antrea.io
  resources:
  - networkpolicies/status
  verbs:
  - create
  - get
  - patch
- apiGroups:
  - controlplane.antrea.io
  resources:
  - nodestatssummaries
  verbs:
  - create
  - patch
- apiGroups:
  - controlplane.antrea.io
  resources:
  - supportbundlecollections
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - controlplane.antrea.io
  resources:
  - supportbundlecollections/status
  verbs:
  - create
  - patch
- apiGroups:
  - crd.antrea.io
  resources:
  - antreaagentinfos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
- apiGroups:
  - crd.antrea.io
  resources:
  - antreacontrollerinfos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
- apiGroups:
  - crd.antrea.io
  resources:
  - clustergroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.antrea.io
  resources:
  - clustergroups/status
  verbs:
  - update
  - patch
- apiGroups:
  - crd.antrea.io
  resources:
  - clusternetworkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.antrea.io
  resources:
  - clusternetworkpolicies/status
  verbs:
  - update
  - patch
- apiGroups:
  - crd.antrea.io
  resources:
  - egresses
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.antrea.io
  resources:
  - egresses/status
  verbs:
  - patch
  - update
- apiGroups:
  - crd.antrea.io
  resources:
  - externalentities
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.antrea.io
  resources:
  - externalippools
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - crd.antrea.io
  resources:
  - externalippools/status
  verbs:
  - patch
  - update
- apiGroups:
  - crd.antrea.io
  resources:
  - externalnodes
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - crd.antrea.io
  resources:
  - groups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.antrea.io
  resources:
  - groups/status
  verbs:
  - update
  - patch
- apiGroups:
  - crd.antrea.io
  resources:
  - ippools
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - crd.antrea.io
  resources:
  - ippools/status
  verbs:
  - patch
  - update
- apiGroups:
  - crd.antrea.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.antrea.io
  resources:
  - networkpolicies/status
  verbs:
  - update
  - patch
- apiGroups:
  - crd.antrea.io
  resources:
  - supportbundlecollections
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - crd.antrea.io
  resources:
  - supportbundlecollections/status
  verbs:
  - update
  - patch
- apiGroups:
  - crd.antrea.io
  resources:
  - tiers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.antrea.io
  resources:
  - traceflows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.antrea.io
  resources:
  - traceflows/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.antrea.io
  resources:
  - trafficcontrols
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - k8s.cni.cncf.io
  resources:
  - network-attachment-definitions
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - multicluster.crd.antrea.io
  resources:
  - clusterinfoimports
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - multicluster.crd.antrea.io
  resources:
  - gateways
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - multicluster.crd.antrea.io
  resources:
  - labelidentities
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - operator.antrea.vmware.com
  resources:
  - antreainstalls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.antrea.vmware.com
  resources:
  - antreainstalls/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - policy.networking.k8s.io
  resources:
  - adminnetworkpolicies
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - policy.networking.k8s.io
  resources:
  - baselineadminnetworkpolicies
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stats.antrea.io
  resources:
  - antreaclusternetworkpolicystats
  verbs:
  - get
  - list
  - patch
- apiGroups:
  - stats.antrea.io
  resources:
  - antreanetworkpolicystats
  verbs:
  - get
  - list
  - patch
- apiGroups:
  - stats.antrea.io
  resources:
  - networkpolicystats
  verbs:
  - get
  - list
  - patch
- apiGroups:
  - system.antrea.io
  resources:
  - agentinfos
  verbs:
  - delete
  - get
  - list
  - post
  - watch
  - patch
- apiGroups:
  - system.antrea.io
  resources:
  - controllerinfos
  verbs:
  - get
  - patch
- apiGroups:
  - system.antrea.io
  resources:
  - supportbundles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - post
  - watch
- apiGroups:
  - system.antrea.io
  resources:
  - supportbundles/download
  verbs:
  - delete
  - get
  - list
  - patch
  - post
  - watch
- nonResourceURLs:
  - /addressgroups
  verbs:
  - get
- nonResourceURLs:
  - /agentinfo
  verbs:
  - get
- nonResourceURLs:
  - /appliedtogroups
  verbs:
  - get
- nonResourceURLs:
  - /debug/pprof
  verbs:
  - get
- nonResourceURLs:
  - /debug/pprof/*
  verbs:
  - get
- nonResourceURLs:
  - /featuregates
  verbs:
  - get
- nonResourceURLs:
  - /loglevel
  verbs:
  - get
- nonResourceURLs:
  - /metrics
  verbs:
  - get
- nonResourceURLs:
  - /networkpolicies
  verbs:
  - get
- nonResourceURLs:
  - /ovsflows
  verbs:
  - get
- nonResourceURLs:
  - /ovstracing
  verbs:
  - get
- nonResourceURLs:
  - /podinterfaces
  verbs:
  - get
- nonResourceURLs:
  - /serviceexternalip
  verbs:
  - get

