name: Go

on:
  pull_request:
    branches:
      - main

jobs:
  bin:
    name: Build binary and run unit tests
    runs-on: [ubuntu-18.04]
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - name: Check-out code
        uses: actions/checkout@v2
      - name: Build antrea-operator binary
        run: make bin
      - name: Run tests
        run: make test
