name: "Issues and PRs lifecycle management"
on:
  schedule:
    # every day at midnight
    - cron: "0 0 * * *"

jobs:
  stale:
    if: github.repository == 'vmware/antrea-operator-for-kubernetes'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'Issues go stale if they have inactive for 90 dayys or more. Remove stale label or comment, or this will be closed in 90 days'
          stale-pr-message: 'PRs go stale if they have been inactive for 90 days or more. Remove stale label or comment, or this will be closed in 90 days'
          stale-issue-label: 'lifecycle/stale'
          stale-pr-label: 'lifecycle/stale'
          days-before-stale: 90
          days-before-close: 90
          exempt-issue-labels: 'lifecycle/frozen'
          exempt-pr-labels: 'lifecycle/frozen'
          remove-stale-when-updated: true
          debug-only: false
          operations-per-run: 200
  skip:
    if: github.repository != 'vmware/antrea-operator-for-kubernetes'
    runs-on: ubuntu-latest
    steps:
      - name: Skip
        run: |
          echo "Skipping lifecyle management because workflow cannot be run from fork"
